spring:
  devtools:
    livereload:
      enabled: false
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: indentity_service
          uri: http://localhost:8080
          predicates:
            - Path=/identity/**
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=/profile/users/**
server:
  port: 8888
